# Generated by Django 5.0.6 on 2025-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_address'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE orders_order ADD COLUMN IF NOT EXISTS order_source varchar(20) NOT NULL DEFAULT 'web';",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='order_source',
                    field=models.CharField(default='web', max_length=20, verbose_name='Manba'),
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE orders_order ADD COLUMN IF NOT EXISTS subtotal_before_discount numeric(10,2) NOT NULL DEFAULT 0;",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='subtotal_before_discount',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chegirmasiz summa'),
                )
            ],
        ),
    ]
