# Generated by Django 5.0.6 on 2025-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_order_source_order_subtotal_before_discount"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE orders_order ADD COLUMN IF NOT EXISTS discount_percent integer NOT NULL DEFAULT 0;",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="order",
                    name="discount_percent",
                    field=models.PositiveIntegerField(default=0, verbose_name="Chegirma (%)"),
                )
            ],
        ),
    ]
