# Generated by Django 5.0.6 on 2025-12-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_discount_percent"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE orders_order ADD COLUMN IF NOT EXISTS discount_amount numeric(10,2) NOT NULL DEFAULT 0;",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="order",
                    name="discount_amount",
                    field=models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Chegirma summasi"
                    ),
                )
            ],
        ),
    ]
