# Generated by Django 5.0.6 on 2025-12-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_discount_amount"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE orders_deliverysettings ADD COLUMN IF NOT EXISTS order_start_time time NULL;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "ALTER TABLE orders_deliverysettings ADD COLUMN IF NOT EXISTS order_end_time time NULL;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="deliverysettings",
                    name="order_start_time",
                    field=models.TimeField(blank=True, null=True, verbose_name="Buyurtma boshlanishi"),
                ),
                migrations.AddField(
                    model_name="deliverysettings",
                    name="order_end_time",
                    field=models.TimeField(blank=True, null=True, verbose_name="Buyurtma tugashi"),
                ),
            ],
        ),
    ]
