# Generated by Django 5.0.6 on 2025-12-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_deliverysettings_order_window"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE orders_order ADD COLUMN IF NOT EXISTS delivery_time_choice varchar(10) NOT NULL DEFAULT 'now';",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "ALTER TABLE orders_order ADD COLUMN IF NOT EXISTS delivery_time time NULL;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="order",
                    name="delivery_time_choice",
                    field=models.CharField(
                        choices=[("now", "Hozirroq"), ("schedule", "Vaqtni tanlash")],
                        default="now",
                        max_length=10,
                        verbose_name="Yetkazish vaqti",
                    ),
                ),
                migrations.AddField(
                    model_name="order",
                    name="delivery_time",
                    field=models.TimeField(blank=True, null=True, verbose_name="Yetkazish vaqti (ixtiyoriy)"),
                ),
            ],
        ),
    ]
