# Generated by Django 5.0.6 on 2025-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_order_delivery_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(db_index=True, max_length=50, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Yangi"),
                    ("accepted", "Qabul qilindi"),
                    ("delivering", "Yetkazilmoqda"),
                    ("finished", "Yakunlangan"),
                ],
                db_index=True,
                default="new",
                max_length=20,
                verbose_name="Holat",
            ),
        ),
    ]
