# Generated by Django 5.0.6 on 2026-01-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybook',
            name='status',
            field=models.CharField(choices=[('unread', "O'qilmagan"), ('reading', "O'qilmoqda"), ('finished', "O'qilgan")], default='unread', max_length=10, verbose_name='Holat'),
        ),
    ]
