# Generated by Django 5.2.7 on 2025-12-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_merge_20251204_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni'),
        ),
    ]
