# Generated by Django 5.0.6 on 2025-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_book_stock_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Muallif"),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Yaratilgan"),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_recommended",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Tavsiya etilgan"),
        ),
        migrations.AlterField(
            model_name="book",
            name="views",
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ko‘rishlar soni"),
        ),
    ]
