# Generated by Django 5.2.7 on 2026-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_catalog_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Sotib olish narxi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Sotish narxi'),
        ),
    ]
